/**
 * Leads Mapper
 *
 * Converts tool input data to Airtable "Leads" table field format.
 */

export interface LeadInput {
  name: string;
  email: string;
  tattooIdea: string;
  placement?: string;
  size?: string;
  color?: string;
  budget?: string;
  notes?: string;
  priceEstimate?: {
    low: number;
    high: number;
  };
  referencePhotoUrl?: string;
}

export interface AirtableLeadFields {
  Name: string;
  Contact: string;
  TattooStyle: string;
  Placement?: string;
  Size?: string;
  Color?: string;
  Budget?: string;
  ReferencePhoto?: Array<{
    url: string;
  }>;
  PriceEstimate?: string;
  Status: "New" | "Contacted" | "Booked" | "Completed" | "Not a fit";
  Source: "Chat Widget" | "Instagram" | "Walk-in" | "Referral";
  Notes?: string;
  // CreatedAt is auto-generated by Airtable (computed field)
}

/**
 * Map lead input to Airtable fields
 *
 * @param input - Lead information from the tool
 * @returns Fields formatted for Airtable
 */
export function mapLeadToAirtable(input: LeadInput): AirtableLeadFields {
  // Map placement - capitalize first letter (e.g., "arm" → "Arm")
  const placementDisplay = input.placement
    ? input.placement.charAt(0).toUpperCase() + input.placement.slice(1).toLowerCase()
    : undefined;

  // Format size - capitalize first letter (e.g., "small" → "Small")
  const sizeDisplay =
    input.size && input.size.length > 0
      ? input.size.charAt(0).toUpperCase() + input.size.slice(1).toLowerCase()
      : undefined;

  // Format color for Airtable select field
  // Airtable expects: "Color" or "Black & Grey"
  let colorDisplay: string | undefined;
  if (input.color) {
    if (input.color.toLowerCase().includes("black")) {
      colorDisplay = "Black & Grey";
    } else if (input.color.toLowerCase().includes("color")) {
      colorDisplay = "Color";
    } else {
      colorDisplay = input.color;
    }
  }

  // Format budget (keep as is)
  const budgetDisplay = input.budget ? input.budget : undefined;

  // Format price estimate
  let priceEstimateDisplay: string | undefined;
  if (input.priceEstimate) {
    priceEstimateDisplay = `$${input.priceEstimate.low} - $${input.priceEstimate.high}`;
  }

  // Map reference photo (Airtable attachment field expects array of objects with url)
  const referencePhoto = input.referencePhotoUrl
    ? [{ url: input.referencePhotoUrl }]
    : undefined;

  return {
    Name: input.name,
    Contact: input.email,
    TattooStyle: input.tattooIdea,
    Placement: placementDisplay,
    Size: sizeDisplay,
    Color: colorDisplay,
    Budget: budgetDisplay,
    ReferencePhoto: referencePhoto,
    PriceEstimate: priceEstimateDisplay,
    Status: "New",
    Source: "Chat Widget",
    Notes: input.notes,
    // CreatedAt is auto-generated by Airtable (computed field) - don't send it
  };
}

/**
 * Create a summary of the lead for logging
 */
export function summarizeLead(input: LeadInput): string {
  const parts = [
    `Name: ${input.name}`,
    `Email: ${input.email}`,
    `Style: ${input.tattooIdea}`,
  ];

  if (input.placement) parts.push(`Placement: ${input.placement}`);
  if (input.size) parts.push(`Size: ${input.size}`);
  if (input.color) parts.push(`Color: ${input.color}`);
  if (input.budget) parts.push(`Budget: ${input.budget}`);
  if (input.priceEstimate) {
    parts.push(
      `Estimate: $${input.priceEstimate.low} - $${input.priceEstimate.high}`
    );
  }

  return parts.join(" | ");
}
